### ISSUE TITLE
ADD MIN MIRROR BOT

### ISSUE THREAD

**Issue by DRAWIZ** [xcscxr/appdrive-dl#1]
hello bro
i need one help

**Comment by ThisIsZek** [comment]
what do you mean by min mirror bot?

**Comment by DRAWIZ** [comment]
https://github.com/drawizmonarch12/Drawiz-Repo

I need to add appdrive bro in this mirror repo bro

**Comment by l3v11** [comment]
> https://github.com/drawizmonarch12/Drawiz-Repo
> 
> I need to add appdrive bro in this mirror repo bro

Yeah do it

**Comment by DRAWIZ** [comment]
> > https://github.com/drawizmonarch12/Drawiz-Repo
> > I need to add appdrive bro in this mirror repo bro
> 
> Yeah do it

Can you do it a new appdrive.py chck my mirror repo and create and send me pls where i can paste bcoz i dont know code
